version: '3.7'

services:
  db:
    container_name: db
    image: mysql/mysql-server:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DATABASE_PORT}:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%

    expose:
      - ${DATABASE_PORT}
